DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	CONSTRAINT NAME_IS_UNIQUE UNIQUE KEY NAME);