DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GAMES;

CREATE TABLE USERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	CONSTRAINT NAME_IS_UNIQUE UNIQUE KEY NAME);

CREATE TABLE GAMES (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	HOSTID REFERENCES USERS(ID),
	NAME VARCHAR(255) UNIQUE NOT NULL,
	MAXPLAYERS INT NOT NULL,
	ISPRIVATE BOOLEAN NOT NULL,
	PASSWORD VARCHAR(255),
	CHECK (MAYPLAYERS >= 4 AND MAXPLAYERS <= 7));
