DROP TABLE IF EXISTS PLAYERS;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	CONSTRAINT NAME_IS_UNIQUE UNIQUE KEY NAME);

CREATE TABLE GAMES (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	MAXPLAYERS INT NOT NULL,
	ISPRIVATE BOOLEAN NOT NULL,
	HASH CHAR(128),
	SALT CHAR(16),
	CHECK (MAYPLAYERS >= 4 AND MAXPLAYERS <= 7));
	
CREATE TABLE PLAYERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USERID REFERENCES USERS(ID),
	GAMEID REFERENCES GAMES(ID),
	ISHOST BOOLEAN NOT NULL);